services:
    lockbymemories_app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: lockbymemories_app
        environment:
            DB_CONNECTION: mysql
            DB_HOST: lockbymemories_db
            DB_PORT: 3306
            DB_DATABASE: lockbymemories
            DB_USERNAME: lockbymemories
            DB_PASSWORD: lockbymemories
        volumes:
            - .:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            lockbymemories_db:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"
    lockbymemories_nginx:
        image: nginx:alpine
        container_name: lockbymemories_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - lockbymemories_app

    lockbymemories_db:
        image: mysql:8.0
        container_name: lockbymemories_db
        restart: always
        environment:
            MYSQL_DATABASE: lockbymemories
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: lockbymemories
            MYSQL_PASSWORD: lockbymemories
        ports:
            - "3306:3306"
        volumes:
            - lockbymemories_dbdata:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ulockbymemories", "-plockbymemories"]
            interval: 5s
            timeout: 5s
            retries: 20

volumes:
    lockbymemories_dbdata:
