services:
    filament_app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: filament_app
        environment:
            DB_CONNECTION: mysql
            DB_HOST: filament_db
            DB_PORT: 3306
            DB_DATABASE: filament
            DB_USERNAME: filament
            DB_PASSWORD: filament
        volumes:
            - .:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            filament_db:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"
    filament_nginx:
        image: nginx:alpine
        container_name: filament_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - filament_app

    filament_db:
        image: mysql:8.0
        container_name: filament_db
        restart: always
        environment:
            MYSQL_DATABASE: filament
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: filament
            MYSQL_PASSWORD: filament
        ports:
            - "3306:3306"
        volumes:
            - filament_dbdata:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ufilament", "-pfilament"]
            interval: 5s
            timeout: 5s
            retries: 20

volumes:
    filament_dbdata:
